apiVersion: v1
kind: Service
metadata:
  name: threat-api-svc
  labels:
    app: threat-api-svc
    tier: backend
spec:
  type: NodePort
  selector:
    app: threat-api-svc
    tier: backend
  ports:
  - port: 8000
    targetPort: 8000
    NodePort: 30080
